const bodyElement = document.querySelector("body");
bodyElement.style.backgroundColor = "#e9e9e9";
const newsElement = document.querySelector(".news");
newsElement.style.backgroundColor = "white";
const headerElement = document.querySelector('h1');
headerElement.classList.add('news__title');
headerElement.textContent = "Aktuální novinky";
const firstPost = document.querySelector("#zprava1");
firstPost.classList.add('post--main');
const thirdPicture = document.querySelector("#zprava3 .post__picture");
thirdPicture.src = "images/zprava3-novy.jpg";
